### PR TITLE
Adding Multi Stage Dockerization

### PR DESCRIPTION
**Pull request by Shipu**
- Multi Stage Dockerization for reduce docker image size.
- Support `php-fpm` Customisable  
- Support `nginx` Customisable 
- Easily update port
- No dependency 
- No need to install `laravel-sail`

### CODE REVIEW

**Comment by AlyateAmine** [comment]
Can u add the documentation link in the readme file 🙏

**Comment by Shipu** [comment]
@AlyateAmine which documentation ? already update readme file. Did I forget something?

**Comment by danharrin** [comment]
Thanks, but we should stick to Laravel Sail as more people are familiar with that.

**Comment by danharrin** [comment]
Plus, I have no Docker experience so can't maintain this.

**Pull request closed without merging**
