### PR TITLE
Migrate from Laravel Mix to Vite

### PR DESCRIPTION
**Pull request by danharrin**
This pull request includes changes for migrating from Laravel Mix to Vite outlined in [Migration Guide](https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md#migrating-from-laravel-mix-to-vite) and automated by the [Vite Converter](https://laravelshift.com/convert-laravel-mix-to-vite).

**Before merging**, you need to:

- Checkout the `shift-66727` branch
- Run `composer update`
- Run `npm install`
- Review **all** comments for additional changes 
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

Please send your feedback to shift@laravelshift.com or share the good vibes on [Twitter](https://twitter.com/laravelshift).

### CODE REVIEW

**Comment by danharrin** [comment]
:information_source: Previously, Laravel configured several npm scripts for building assets. For Vite, Laravel configures a `dev` script for generating and watching your assets (for development) and `build` script for generating your assets (for production).

Shift attempted to replace commands using these scripts with their new Vite script. However, you may still be referencing these scripts in your code or in deployment scripts.

**Comment by danharrin** [comment]
:information_source: Vite requires JavaScript files containing JSX to have a `.jsx` file extension. Shift did not detect any JSX in files with a `.js` extension under the `resources` folder. However, if you are using JSX, be sure the files have a `.jsx` extension.

**Comment by danharrin** [comment]
:warning: Vite generates frontend assets to the `public/build` folder. This folder is not tracked by Git within a default Laravel project. As such, Shift added this folder to your `.gitignore` file.

If you wish to track the generated frontend assets within your project, such as for ease of deployment, you may undo [this commit](https://github.com/filamentphp/demo/pull/36/commits/f7a55d058f7a7473b87f2988126c1bd712550144?w=1) by running `git revert f7a55d05`.

**Comment by danharrin** [comment]
:alembic: This Shift is still being refined. **Please report any issues or suggestions** to [shift@laravelshift.com](mailto:shift@laravelshift.com). Your feedback is what helps improve the experience for everyone.

**Comment by pxlrbt** [comment]
That shift doesn't have any effect on the Demo, as we don't use a custom theme, right?

**Comment by danharrin** [comment]
Yeah but we still had Mix installed so

**Pull request merged**
