### PR TITLE
Fix deprecations & Bump PHPStan level

### PR DESCRIPTION
**Pull request by Z3d0X**
- Replaces the deprecated methods.
- adds dev dependency `phpstan/phpstan-deprecation-rules` - deprecated code detection for phpstan

### CODE REVIEW

**Review by danielhe4rt — APPROVED** [review]

**Comment by danharrin** [comment]
Hey @Z3d0X ! Sorry for not seeing this sooner. How much of this is still relevant?

**Comment by Z3d0X** [comment]
@danharrin Updated! phpstan (w/ `phpstan/phpstan-deprecation-rules` plugin) passes at current configured level of 5.

If you want i bump phpstan to a higher level

**Comment by danharrin** [comment]
if you want to work on fixing it for a higher level, go for it! but if not, dont worry about it

**Comment by Z3d0X** [comment]
@danharrin all done

**Comment by danharrin** [comment]
Thank you so much!

**Pull request merged**
