### PR TITLE
Validate customer birthday

### LINKED ISSUE #31: Validate customer birthday
### Package

filament/filament

### Package Version

have no idea 

### Laravel Version

have no idea

### Livewire Version

have no idea

### PHP Version

have no idea

### Bug description

image
As you can see in the above image the date of birth calendar allows us to select future dates right? it should not be allowed to us. it should be disabled in the calendar.

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by zepfietje**

### CODE REVIEW

**Comment by zepfietje** [comment]
Thanks, @shuvroroy!

**Comment by pxlrbt** [comment]
@zepfietje I think you can tag @shuvroroy and me on these for review. Dan has enough to do with the core repos.

**Comment by zepfietje** [comment]
> @zepfietje I think you can tag @shuvroroy and me on these for review. Dan has enough to do with the core repos.

Yeah that was my thinking as well, but was not sure if you guys could merge. Thanks for the notice!

**Comment by pxlrbt** [comment]
I think all of us can merge.

**Comment by zepfietje** [comment]
Yeah, but for the main repository there's the rule that only Dan merges. That's why I wasn't sure.

**Comment by danharrin** [comment]
Yeah go for it, everyone merge here

**Pull request merged**
